baseurl      = "https://continueproject.com"
title        = "The Continue Project"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
googleAnalytics = "UA-4880035-39"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "While this body contains breath, I will continue."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "While this body contains breath, I will continue."
  keywords = "engineering, software development, mental health, suicide prevention"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "light"

  footerRight = "Theme Made With &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "The Continue Project"
    subtitle = "While this body contains breath, I will continue."
    keywords = "engineering, software development, mental health, suicide prevention"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "continue;"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
    [[menu.main]]
      identifier = "blog"
      name       = "Blog"
      url        = "/posts"
    [[menu.main]]
      identifier = "about"
      name       = "About"
      url        = "/about"